version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Build client and backend docker images for testing...
      - docker build -t ohiji_frontend/react-test -f ./Dockerfile.dev .
  build:
    commands:
      # Run tests with built Docker images
      - echo Run react tests...
      # 設定 -e CI=true 可以讓 test 只運行一次就退出 
      - docker run -e CI=true ohiji_frontend/react-test
      # Build the Docker images
      - echo Building the production Docker image...
      - docker build -t ohiji_frontend/reactjs-onlinestore-frontend .
      # Log in to the Docker CLI
      - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  post_build:
    commands:
      # Take these images nad push them to Docker hub
      - echo Pushing the Docker images...
      - docker push ohiji_frontend/reactjs-onlinestore-frontend
